WIP: Try to build crun to use with Podman
TODO:
```
src/libcrun/cloned_binary.c:559:2: error: call to undeclared function 'fexecve'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  559 |         fexecve(execfd, argv, environ);
      |         ^
src/libcrun/cloned_binary.c:559:2: note: did you mean 'execve'?
/home/builder/.termux-build/_cache/android-r27c-api-24-v1/bin/../sysroot/usr/include/unistd.h:147:5: note: 'execve' declared here
  147 | int execve(const char* _Nonnull __file, char* _Nullable const* _Nullable __argv, char* _Nullable const* _Nullable __envp);
      |     ^
1 error generated.
make[2]: *** [Makefile:1856: src/libcrun/libcrun_la-cloned_binary.lo] Error 1
  CC       src/libcrun/libcrun_la-signals.lo
  CC       src/libcrun/libcrun_la-status.lo
src/libcrun/utils.c:1860:9: error: call to undeclared function 'eaccess'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1860 |   ret = eaccess (path, X_OK);
      |         ^
src/libcrun/utils.c:1860:9: note: did you mean 'access'?
/home/builder/.termux-build/_cache/android-r27c-api-24-v1/bin/../sysroot/usr/include/pwd.h:98:5: note: 'access' declared here
   98 | int access(const char* __path, int __mode);
      |     ^
1 error generated.
make[2]: *** [Makefile:1779: src/libcrun/libcrun_la-utils.lo] Error 1
  CC       src/libcrun/libcrun_la-terminal.lo
src/libcrun/scheduler.c:97:36: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
   97 |   ret = sched_setaffinity (pid, 0, NULL);
      |                                    ^~~~
/home/builder/.termux-build/_cache/android-r27c-api-24-v1/lib/clang/18/include/__stddef_null.h:26:14: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |              ^~~~~~~~~~
src/libcrun/linux.c:3332:9: error: call to undeclared function 'setdomainname'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3332 |   ret = setdomainname (def->domainname, strlen (def->domainname));
      |         ^
1 warning generated.
1 error generated.
make[2]: *** [Makefile:1968: src/libcrun/libcrun_la-linux.lo] Error 1
make[2]: Target 'all-am' not remade because of errors.
make[2]: Leaving directory '/home/builder/.termux-build/crun/src'
make[1]: *** [Makefile:2649: all-recursive] Error 1
make[1]: Leaving directory '/home/builder/.termux-build/crun/src'
make: *** [Makefile:1070: all] Error 2
```